.cirrus.yml, ci/Containerfile, ci/Dockerfile, ci/install_packages.sh, ci/install_packages.txt
=> Configure basic CI environment and stub test

.cirrus.yml, .mergify.yml
=> Enable mergify + Cirrus-CI

.mergify.yml
=> WIP: Temporarily disable review request requirement

.mergify.yml, README.md
=> Add contribution notes

packer/.gitignore, packer/Makefile, packer/cloud-init/fedora/cloud-init.service, packer/cloud-init/fedora/cloud.cfg.d/40_enable_root.cfg, packer/cloud-init/fedora/cloud.cfg.d/50_custom_disk_setup.cfg, packer/cloud-init/ubuntu/cloud.cfg.d/40_enable_root.cfg, packer/fedora_base-setup.sh, packer/fedora_packaging.sh, packer/fedora_setup.sh, packer/image-builder-image_base-setup.sh, packer/libpod_base_images.yml, packer/libpod_images.yml, packer/make-user-data.sh, packer/prior-fedora_base-setup.sh, packer/systemd_banish.sh, packer/ubuntu_packaging.sh, packer/ubuntu_setup.sh
This is the latest `contrib/cirrus/packer` directory from the
`containers/podman` repository more/less as-is at the time
of this commit.  Only (now) irrelivent documentation was
removed.
=> Copy containers/podman packer setup

.cirrus.yml, base_images/gce.yml, image_builder/gce.yml
=> Store successful build manifest artifact

.cirrus.yml, Makefile, base_images/fedora_base-setup.sh, base_images/gce.yml, base_images/ubuntu_base-setup.sh, lib.sh
=> Install common tooling in base-images

.mergify.yml, README.md
=> Enable PR review requirement

.cirrus.yml, Makefile, README.md, base_images/gce.yml, base_images/no_dash.dat, base_images/ubuntu_base-setup.sh, cache_images/fedora_packaging.sh, cache_images/fedora_setup.sh, cache_images/gce.yml, cache_images/podman_tooling.sh, cache_images/ubuntu_packaging.sh, cache_images/ubuntu_setup.sh, ci/make_cache_images.sh, ci/shellcheck.sh, image_builder/gce.yml, lib.sh, systemd_banish.sh
=> Implement building cache_images

.cirrus.yml, Makefile, README.md
=> Minor comment/docs fixes

.cirrus.yml, Makefile, README.md, base_images/fedora_base-setup.sh, base_images/ubuntu_base-setup.sh, cache_images/fedora_packaging.sh, cache_images/fedora_setup.sh, cache_images/ubuntu_setup.sh, image_builder/install_packages.sh, image_builder/install_packages.txt, lib.sh, podman/Containerfile, podman/setup.sh
=> Migrate in_podman containers

.cirrus.yml, Makefile, lib.sh
=> Only run image builds for PRs

.cirrus.yml
=> Also skip branch container builds

cache_images/fedora_packaging.sh, cache_images/ubuntu_packaging.sh, lib.sh
=> Ubuntu download of crun package

.cirrus.yml, Makefile, ci/make_container_images.sh, imgprune/Containerfile, imgprune/README.md, imgprune/entrypoint.sh, imgts/Containerfile, imgts/README.md, imgts/entrypoint.sh, imgts/google-cloud-sdk.repo, imgts/lib_entrypoint.sh
=> Add VM-Image management containers

imgobsolete/entrypoint.sh, imgprune/entrypoint.sh
Ref: https://github.com/containers/automation_images/pull/29#discussion_r509624867
=> Fix depr. comparison + add comments

cache_images/fedora_packaging.sh, cache_images/ubuntu_packaging.sh
=> Add python3-docker package

cache_images/fedora_packaging.sh
See https://github.com/containers/podman/pull/8297
=> Fedora perl package needed by podman docs checking

cache_images/fedora_packaging.sh
Signed-off-by: baude <bbaude@redhat.com>
=> add compose to fedora

imgts/entrypoint.sh
According to google-cloud support, over the past year, less than 1%
of VM Image label updates clashed with other simultaneous label updates.
When this occurs, an error and message is returned by the gcloud
command:
```
ERROR: (gcloud.compute.images.update) HTTPError 412: Labels fingerprint
either invalid or resource labels have changed
```
Perhaps worse, this causes the label update job in automation to fail,
and require attention from the developer.  Avoid this situation by
detecting this specific condition, issuing a warning, then ignoring it.
This is safe because:
* There are no other automation processes or manual provisions currently
in use which touch VM Image labels in any way.
* The label update operations are atomic on the cloud-side, this is how
they are able to detect the error …
=> Fix label update clash

README.md
=> Update conmon package in images

README.md
For https://github.com/containers/buildah/pull/2631
=> VM Images for driver=overlay fix in Ubuntu packages

.cirrus.yml, Makefile, base_images/fedora_base-setup.sh, base_images/ubuntu_base-setup.sh, gcsupld/Containerfile, gcsupld/README.md, gcsupld/entrypoint.sh, gcsupld/test.sh, imgobsolete/README.md, imgprune/README.md, imgts/README.md, lib.sh
Also update other container image directories to correct example build
instructions.
=> Add container image for uploading files to GCS

cache_images/fedora_packaging.sh
Ref:
* https://github.com/containers/podman/pull/9300
* https://github.com/containers/podman/pull/9245
=> Rebuild images to update runc and crun

README.md
=> Produce updated VM images

cache_images/fedora_packaging.sh
Ref: https://github.com/containers/podman-py/pull/63
=> Add packages needed by podman-py

cache_images/fedora_packaging.sh, cache_images/ubuntu_packaging.sh
We've got tests that need to use the `zstd` CLI tool coming soon.
=> Add `zstd` to images

.cirrus.yml
=> [CI:DOCS] Fix YAML anchor/alias image_family conflict

.cirrus.yml, README.md, ci/make_container_images.sh, get_ci_vm/entrypoint.sh, get_ci_vm/test.sh
* Update status/debug messages
* Fix attempt to copy removed files from repo.
* Disable printing detached-head git message
=> [CI:LATEST] Minor: Several small get_ci_vm fixes

.cirrus.yml, README.md, get_ci_vm/setup.sh, lib.sh
=> [CI:TOOLING] Fix bug introduced in automation 2.1.3

.github/workflows/pr_image_id.yml
=> [CI:DOCS] Fix commenting image ID on unsuccessful build

Makefile, base_images/gce.yml, get_packer_version.sh, lib.sh
=> Update from beta to released F34

cache_images/fedora_packaging.sh
=> Add python pyxdg and wheel

.cirrus.yml, .github/workflows/orphan_vms.yml, Makefile, gcpprojects.txt, gcsupld/README.md, imgobsolete/README.md, imgprune/README.md, imgts/README.md, orphanvms/Containerfile, orphanvms/README.md, orphanvms/entrypoint.sh
=> [CI:TOOLING] Add orphan-vms tooling container

.github/workflows/orphan_vms.yml
=> [CI:DOCS] Fix minor action issues

README.md, base_images/gce.yml
=> Update ubuntu base + refresh all packages

cache_images/ubuntu_packaging.sh
=> Fix missing gofmt binary in Ubuntu

README.md
=> [CI:DOCS] Update VM Image build docs

cache_images/fedora_packaging.sh
=> Fix workaround due to obsolete update

cache_images/fedora_packaging.sh
This needs to be followed by a (*FIXME* removal) change to https://github.com/containers/podman/blob/f9d8301c476fcd8498930c518f04920e9e8eeac5/contrib/cirrus/setup_environment.sh#L212-L215
=> DL packages for podman docker-py tests

lib.sh
=> [CI:DOCS] Update Ubuntu finalize comment

cache_images/fedora_packaging.sh, cache_images/ubuntu_packaging.sh
Ref: https://github.com/containers/podman/issues/12851
=> Add git-daemon packages to all distros

image_builder/gce.yml
Tested change via #111 - no need to build images in this PR.
=> [CI:DOCS] Use CentOS-8 Stream for Image Builder VM

cache_images/fedora-netavark_packaging.sh, cache_images/fedora_packaging.sh
Ref: https://github.com/containers/aardvark-dns/pull/68 and https://github.com/containers/netavark/pull/187
=> Add packages for netavark/aardvark CI

cache_images/fedora-netavark_packaging.sh
Signed-off-by: Brent Baude <bbaude@redhat.com>
=> Add packages for running podman e2e in netavark

lib.sh
=> Freshen VM images + upgrade automation library

base_images/gce.yml, build-push/bin/main.sh, build-push/test.sh, cache_images/fedora_packaging.sh, get_ci_vm/entrypoint.sh, lib.sh, orphanvms/entrypoint.sh
Companion to https://github.com/containers/automation/pull/96
Also includes a minor update to resume caching packages in CI container images.
=> [WIP] Use automation-lib v4.0 w/ `$DEBUG` fix

.cirrus.yml, cache_images/cloud.yml, cache_images/podman_tooling.sh
@cevich piggybacks on your https://github.com/containers/automation_images/pull/132
=> Aws support podman

get_ci_vm/entrypoint.sh
This will be required by a future security policy.
=> [CI:TOOLING] Minor: Include instance automation tag

README.md, get_ci_vm/README.md
For too long, most of this has had a single source: My Skull.  Attempt to spell it out for others benefit (maybe).
=> [CI:DOCS] Add get_ci_vm script-interface documentation

.github/workflows/orphan_vms.yml
An attempt to re-fix https://github.com/containers/automation_images/pull/171
Ref: https://github.com/containers/automation_images/issues/173
=> [CI:DOCS] Use --env-host for podman 3.4.4

.github/workflows/orphan_vms.yml
Ref: https://github.com/containers/automation_images/issues/173
=> [CI:DOCS] Fix file-redirect typo

.github/actions/bin/create_image_table.py
=> [CI:DOCS] Fix image build ID script syntax

imgobsolete/entrypoint.sh
Fixes: #186 ([Example log](https://cirrus-ci.com/task/5398202080821248))
For whatever reason, the `aws` CLI does not exit non-zero if there was
an error obsoleting an image.  Worse, it forces callers to verify a JSON
blob as well.
Fix this, and improve the script by accumulating any errors and exiting
non-zero after the entire loop finishes.  In the case of `aws`,
additionally verify the output JSON provides positive confirmation of a
successful update.
=> [CI:TOOLING] Fix silent imgobsolete error + check status JSON

.github/actions/bin/create_image_table.py
=> [CI:DOCS] Fix syntax error + other flake8 style findings

.github/actions/bin/create_image_table.py, .github/workflows/pr_image_id.yml
Based on observations, CWD is (somehow) not always available in all contexts.
=> [CI:DOCS] Write to files in $GITHUB_WORKSPACE instead of CWD

.github/workflows/pr_image_id.yml
Followup to https://github.com/containers/automation_images/pull/199
=> [CI:DOCS] Ensure manifest JSON output in $GITHUB_WORKSPACE

.github/workflows/pr_image_id.yml
=> [CI:DOCS] Fix broken env. var reference in action

.github/workflows/pr_image_id.yml
=> [CI:DOCS] Fix missed filepath in previous commit.

.github/actions/bin/create_image_table.py
=> Fix argument-order typo

cache_images/fedora-netavark_packaging.sh
Fixes: #150
**Note**: Requires update in downstream CI setup to remove any rustup commands.
=> Install rust toolchain + clippy for linting

.cirrus.yml, build-push/test.sh
=> Enhanced build push tests

import_images/README.md
Ref: https://github.com/containers/automation_images/pull/302#issuecomment-1735721791
=> [CI:DOCS] Improve import-image docs

.cirrus.yml
Moved to: https://github.com/containers/image_build
=> [CI:DOCS] Migrate quay.io container image build

get_ci_vm/README.md
The readme contained a lot of technical/implementation details, but lacked an overview of the architecture/operations.  Fix this.
=> [CI:DOCS] Improve get_ci_vm container docs

ci/validate.sh
Unfortunately this value doesn't properly reflect the current branch point of a PR.  Replace it with a call to `git merge-base` instead.
Ref: https://github.com/cirruslabs/cirrus-ci-docs issue number 1279
=> [CI:DOCS] Remove broken CIRRUS_BASE_SHA usage
