containers/automation_images

lib.sh
Occasionally for some unknown reason, when booting a base-image to make
a cache-image, the configured apt repositories no-longer function.
Returning errors such as:
```
E: Failed to fetch
http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/eoan/universe/cnf/Commands-amd64
lzma_read: Read error (7)
E: Some index files failed to download. They have been ignored, or old ones used instead.
<exit 100>
```
As /etc/apt/sources.list (containing the above repo) is setup by
cloud-init, attempt to fix the problem by restoring the default sources
list.  This should allow either:
1) cloud-init to configure future-functional sources
2) Fall back to the default distro-configured (upstream) sources.
=> Fix bad ubuntu repos on reboot

.cirrus.yml, Makefile, README.md
This fills out the automation-portion of the processes.  I intend to followup in another PR, with details on manually performing these tasks.  i.e. using the `Makefile` locally.
=> Complete image-building automation docs

cache_images/fedora_packaging.sh, cache_images/ubuntu_packaging.sh
Due to bug https://bugs.launchpad.net/ubuntu/+source/bats/+bug/1882542
which also affects setting things like `$IFS` a fixed version of Bats
is installed from source.  This is done using the containers/podman
Makefile, `install.tools` target for ease of maintenance.
See also: https://github.com/containers/podman/pull/6515
=> Use fixed-version of BATS

.cirrus.yml, Makefile, README.md, imgobsolete/Containerfile, imgobsolete/README.md, imgobsolete/entrypoint.sh, imgprune/README.md, imgprune/entrypoint.sh, imgts/entrypoint.sh, imgts/lib_entrypoint.sh
Previously, successfully updating VM image metadata was treated as
optional (errors ignored).  This resulted in unrelated failures
(e.g. auth. token expiring) going unnoticed.  Consequentially VM
images that were in-use got deleted without warning.  Fix this by
making the operations within `imgts` mandatory (do not ignore
failures).
To further protect VM images from being removed while in use, introduce
a new container image `imgobsolete`, to be run before `imgprune`.
Instead of deleting images, they will be marked as 'deprecated' and
'obsolete' by this new container.  It will also encode advisory
deletion-date metadata, set 30 days into the future.
Lastly, update the `imgprune` container image such that it only searches for
images marked 'deprecated' and 'obsolete' with a metadata …
=> Re-implement image life-cycle management

cache_images/ubuntu_packaging.sh, lib.sh
Conmon testing (the only consumer of the cri-o package) only
tests Fedora, there is no need for this package to be present on Ubuntu
VMs.  Remove it to reduce future maintenance burden.
=> Remove cri-o from Ubuntu VM images

base_images/fedora_base-setup.sh, base_images/gce.yml, cache_images/fedora_packaging.sh, cache_images/fedora_setup.sh, cache_images/ubuntu_packaging.sh
Provide more disk space for podman's static-build task cache-restoration.
=> Enlarge fedora VM starting disk

.cirrus.yml
There's no useful workflow based on images built during branch or tag
push, only pull-requests.  Further, there is no reason to build anything
during Cirrus-Ci cron-triggered builds.
=> Only build images in PRs

lib.sh
This permits breaking changes to merge into `containers/automation`
without unexpectidly breaking any downstream usage.
Ref: https://github.com/containers/automation/pull/58
=> Lock to static automation library version

cache_images/fedora_packaging.sh, cache_images/ubuntu_packaging.sh
Including this allows c/storage testing to operate w/o
installing/upgrading packages at runtime.  This is desired
as it (generally) improves reliability.
=> Include package needed for c/storage testing

gcsupld/entrypoint.sh
In case of unexpected `tr` or `wc` output, make sure it's shown in the
error message.
=> Minor logic & debug-ability fixes

cache_images/fedora_packaging.sh
This is needed for some last-minute requirements in podman v3.0.  The
entire commit may be safely reverted after these packages land in the
mainstream repositories (i.e. 'updates' for F32 and 'updates-testing'
for F33).
=> Temporarily include specific conmon Fedora update

cache_images/fedora_packaging.sh
It was observed in freshly built F33 VM images, dnf install doesn't
always get you the latest/greatest packages.  Fix this with a big-
hammer (I don't understand the problem) by running a second package
update after installing.
=> Update packages on Fedora again, after installing

.cirrus.yml
Fixes #51
Several container images (like `imgobsolete`) are mostly/mainly
utilized by reference to their 'latest' tag.   The
`container_images_task` is configured to push a 'latest' tag.  However,
that job only runs for PRs, so never actually did this task.
Fix this and add a dedicated job for building/pushing `latest`
tagged images during branch-push (includes PR merge).
=> [CI:DOCS] Build & push 'latest' container images

cache_images/ubuntu_packaging.sh
Remove ubuntu golang and add upstream golang to avoid their
non-performant golang
Signed-off-by: baude <bbaude@redhat.com>
=> Add upstream golang for ubuntu

ci/make_container_images.sh, lib.sh
It is/was an error to force `PUSH_LATEST` to 0, this should simply be a
default.
=> [CI:LATEST] Fix never pushing latest images

.github/workflows/pr_image_id.yml
It's a common burden to lookup the newly produce VM/Container image ID
produced by automation.  Add a github action which detects Cirrus-CI
'success' and publishes a comment containing a link and the image ID
value.
It's not possible to test this inside a PR here (action code must
exist on master branch).  Test was performed manually here:
https://github.com/containers/automation_sandbox/pull/88
=> [CI:DOCS] Add action to post image ID to PR on success

lib.sh
Required for get_ci_vm support of `macos_instance` type.
=> [CI:LATEST] Update automation library to 2.1.3

lib.sh
This is required to account for the default branch change in
containers/automation.
=> Bump automation lib. version

.github/workflows/orphan_vms.yml
Also, tee the output so it may be observed w/o downloading the artifacts
archive.
=> [CI:TOOLING] Fix orphan-vm detection workflow typos

.github/workflows/orphan_vms.yml, orphanvms/entrypoint.sh
There are cases where users have "play" VMs that are normally shutdown
when not in use.  The monitor was falsely triggering on them when
running, due to their very long create-time based age.  Switch to using
the start-time, which will be more accurate in all use cases.
=> [CI:TOOLING] orphanvms: trigger on start instead of create time

cache_images/gce.yml
This may be necessary for example, for testing out NUMA features.
Google doesn't provide any control over NUMA for VMs it provisions.
=> Enable future use of nested VMs

.cirrus.yml, Makefile, README.md, cache_images/fedora_setup.sh, ci/make_container_images.sh, image_builder/Containerfile, imgts/Containerfile, imgts/google-cloud-sdk.repo, skopeo_cidev/Containerfile, skopeo_cidev/README.md, skopeo_cidev/packages.txt, skopeo_cidev/setup.sh
This is significantly different from the podman images (used by
buildah and podman CI).  Namely, it includes several different registry
executables needed during Skopeo's integration and system-tests.
Pre-building these into a container saves developer time locally and in
waiting for changes to pass CI testing.
Also, modernize the registry server login to use the `--password-stdin`
scheme instead of encrypting the entire command-line.
=> Implement build for Skopeo devel/CI container image

Makefile, README.md, cache_images/fedora_setup.sh, image_builder/Containerfile, imgts/Containerfile, imgts/google-cloud-sdk.repo
At some point in the near future, CentOS 8 will stop being maintained.  Since all of our container-based tooling relies on this, best to get it all working on the new Stream-8 base.
Also included is a really important fix for a bug/problem resulting in CGv2 **NOT** getting disabled in F33 (it was previously) as intended.
=> Update to Centos 8 Stream + Other important fixes.

orphanvms/entrypoint.sh
When the 'persistent=true' label is found, simply ignore them when
reporting on any orphans.
=> [CI:TOOLING] Support the existence of persistent VMs

skopeo_cidev/Containerfile
=> [CI:TOOLING] Fix skopeo image locale env. vars.

.cirrus.yml, .gitignore, Makefile, ci/Containerfile, gcsupld/Containerfile, imgobsolete/Containerfile, imgprune/Containerfile, imgts/Containerfile, lib.sh, orphanvms/Containerfile
A substantial amount of time is spent refreshing packaging metadata and
downloading packages during build.  Since consecutive builds from
essentially the same contents does this repeatedly, duplicating all that
work is redundant.  This set of changes causes Cirrus-CI to maintain a
cache of packages and metadata for re-use at container build time.
=> Improve container build performance w/ caching

.cirrus.yml, cache_images/fedora-netavark_packaging.sh, cache_images/fedora_setup.sh, cache_images/gce.yml
The CI needs of the netavark project are significantly different
from the other golang-based projects.  Add a dedicated VM image
for the project, based on the latest Fedora base image.
=> Add fedora-netavark VM image

.github/workflows/check_cirrus_cron.yml
Also add a Cirrus-cron checking job (same as used on other container
repos.) to verify the daily VM image maintenance jobs are successful.
=> [CI:DOCS] Github workflows: Notify on job failure

.github/workflows/check_cirrus_cron.yml
The documentation is less than clear on which magic token gives you the
run number component of the URL.  I think `run_id` is the correct one.
=> Github workflow: Fix error-notice e-mail content.

README.md
This is to ensure VM images for CI, which contain the
intended dependency versions to support the podman
4.0 release.
=> Trigger build of fresh VM  images for podman 4.0

cache_images/fedora-netavark_packaging.sh
The Fedora rust toolchain is fairly old, especially for a young
language.  It also does not include the rustup utility which is
hampering netavark/aardvark-dns development.  Rather than wait for
Fedora to catch up, install the upstream toolchain and utilities.
=> Netavark: Install rust from upstream

cache_images/fedora-netavark_packaging.sh
No need for new images, these tools are currently installed
at CI runtime.  Next round of images updates will pick them up.
=> [CI:DOCS] Minor: Add some build tools for netavark

get_ci_vm/entrypoint.sh
When initializing, gcloud will check for a special ssh key under
~/.config/gcloud/ssh.  When absent, it will generate a new one and
prompt the user for a passphrase.  If a passphrase is set, it will be
requested again for every single gcloud operation, with no possibility
to add it to a desktop keychain.  To help prevent this aggravation,
include it in a warning message at initialization time.
=> [CI:DOCS] Add get_ci_vm warning about ssh key passphrases

build-push/bin/tag_version.sh, build-push/test.sh, cache_images/fedora-netavark_packaging.sh
The prior github-actions implementation prefixed version-tags with a 'v'
character.  Since this letter could (for some contexts) be part of the
version-number read in from the application, ensure the mod-script
strips it out before adding it's own 'v' prefix.
=> Fix build-push version-tagging

build-push/.install.sh, cache_images/build-push_packaging.sh
***This is part one, part two is in https://github.com/containers/netavark/pull/272***
A future commit will add an auto-update feature to main.sh.  This
requires an installation script which can be shared with both VM image
composition and auto-updating.  The installation script must exist first
on the main branch, before the auto-update feature can be committed.
=> Add installation script for build-push main.sh

build-push/bin/tag_version.sh, build-push/test.sh
Since these images build daily, and the full (X.Y.Z) version could
change at any time, it may be difficult for downstream users to track a
uniform FQIN while also receiving security updates.  Since all tags of
produced manifest-lists are already pushed, simply update the
tag_version.sh mod-script to produce the additional tagged
manifest-lists.  Verify this has happened by enhancing the CI test to
check for the new tags.
=> Build-push: Also tag vX.Y and vX stable images

.cirrus.yml, build-push/lib/autoupdate.sh
Related to https://github.com/containers/automation_images/pull/123 the
installer checks that it's running under an expected environment.  This
is always the case under test, but not under normal runtime conditions.
Fix this by making sure the check-variable is available to the installer
when auto-updating.
Also, update CI config so test-build-push task uses the latest
build-push image by family-name instead of the image tied to the PR.
This allows testing to occur under both normal and (magic)
`[CI:TOOLING]` PRs.
=> [CI:TOOLING] Fix runtime check of non-exported variable

build-push/lib/autoupdate.sh
When auto-updating, ensure the new version is re-exec'd from the same
starting directory is was originally called from.  This is required
because the context-directory argument is a relative path (by design).
Also add a reminder that touching the autoupdate.sh script itself, does
require building/deploying new VM images.
=> Fix re-exec outside of starting dir.

cache_images/fedora_packaging.sh
Specifically, the 'dnsname' CNI plugin is needed by CI testing in
containers/common.  Download it into the VM for installation at runtime.
=> Download/cache 'podman-plugins' package in Fedora

skopeo_cidev/Containerfile
... primarily so that it accepts OCI-formatted images.
Proof of concept, as well as other updates necessary to work with that registry version, are in https://github.com/containers/image/pull/1574 .
See https://github.com/containers/skopeo/issues/1673 for more context.
=> Update the registry used for Skopeo CI to 2.8.1

cache_images/fedora_packaging.sh, cache_images/podman_tooling.sh, cache_images/ubuntu_packaging.sh
Fixes https://github.com/containers/automation_images/issues/139
N/B: Using these images requires an update to the podman repo. to remove
the bats installer script and `Makefile` target.
=> Use packaged bats in Fedora, side-load for Ubuntu

.cirrus.yml, README.md, ci/make_base_images.sh, ci/make_cache_images.sh, ci/make_container_images.sh, ci/make_image_builder.sh, imgts/entrypoint.sh, imgts/lib_entrypoint.sh, lib.sh
With an ever growing number of images to build, it's inevitable that
a flake will occur on an image the author does not care about.  Should
this occur, provide a runtime-method by which a 'no_<name>' label can be
added to the PR before re-running the failure.  The specified `<name>`
build will then be bypassed.
Note: This will not bypass container tooling images (they're always
required). Nor will it properly handle any build dependencies.
For example a `no_fedora` label will cause a build failure of the
`build-push` image, since it depends on the `fedora` base image.
=> Skip specified image builds based on PR labels

.cirrus.yml, cache_images/cloud.yml
piggybacks on https://github.com/containers/automation_images/pull/143 
@cevich PTAL
=> Specify arm64 in relevant tasks for clarity

get_ci_vm/good_repo_test/.cirrus.yml, get_ci_vm/test.sh, lib.sh
Specifically, v4.1.1 includes a fix for `get_ci_vm` so it doesn't barf
when encountering `ec2_instance`.  Tested by manually building the
container image and running it using podman's `hack/get_ci_vm.sh`
script.  Found the `--list` operation behaves correctly.  Found the
correct/expected error message is returned when requesting a VM for an
`ec2_instance` task.
=> [CI:TOOLING] Upgrade automation library

cache_images/fedora-netavark_packaging.sh, get_ci_vm/test.sh, lib.sh
These packages should _never_ be pre-installed in the CI images for
testing in the netavark & aardvark-dns repositories.  Ensure they aren't
brought in by a package update in addition to the install.
=> Fix dnf update installing netavark/aardvark-dns

.github/workflows/pr_image_id.yml, ccia/Containerfile, ccia/README.md, ccia/fake_manifests/Image-builder image/manifest/image_builder/manifest.json, ccia/fake_manifests/build-push Cache Image/manifest/cache_images/manifest.json, ccia/fake_manifests/fedora Base Image/manifest/base_images/manifest.json, ccia/fake_manifests/fedora Cache Image/manifest/cache_images/manifest.json, ccia/fake_manifests/fedora-aws Base Image/manifest/base_images/manifest.json, ccia/fake_manifests/fedora-aws Cache Image/manifest/cache_images/manifest.json, ccia/fake_manifests/fedora-aws-arm64 Base Image/manifest/base_images/manifest.json, ccia/fake_manifests/fedora-netavark Cache Image/manifest/cache_images/manifest.json, ccia/fake_manifests/fedora-netavark-aws-arm64 Cache Image/manifest/cache_images/manifest.json, ccia/fake_manifests/fedora-podman-aws-arm64 Cache Image/manifest/cache_images/manifest.json, ccia/fake_manifests/fedora-podman-py Cache Image/manifest/cache_images/manifest.json, ccia/fake_manifests/ubuntu Base Image/manifest/base_images/manifest.json, ccia/fake_manifests/ubuntu Cache Image/manifest/cache_images/manifest.json, ccia/test.sh
This is intended as a help to developers updating images in other repo's
CI systems.  Esp. WRT AWS AMI ID's being utterly unreadable by humans.
Use a bit of `jq` and markdown magic to produce a nice looking table of
image names and IDs.
=> [CI:TOOLING] Print names & IDs of all built images

cache_images/ubuntu_packaging.sh
Upstream podman CI needs to update to a golang 1.18 minimum requirement.
Ensure that version is present in Ubuntu 22.04 images.  DO NOT produce
any prio-fedora images as testing there will be temporarily suspended
until the F37 timeframe.
**Note: Will be incorporated into #152**
=> [CI:DOCS] Support only golang 1.18

.github/workflows/pr_image_id.yml
It's possible a PR does not build the CCIA image for one reason or
another.  When this is the case, fall back to using the most recent
container image.
Ref:  [Example failure](https://github.com/containers/automation_images/actions/runs/2705456090)
=> [CI:TOOLING] Minor: Fix ID comment bot for PR's w/o CCIA builds

.github/workflows/pr_image_id.yml
Apparently in github actions workflow, nested env. vars. do not resolve
like they do in Cirrus-CI.  Fix this.
=> [CI:DOCS] Fix oversight in image ID commenting bot

cache_images/ubuntu_packaging.sh, cache_images/ubuntu_setup.sh
PR #115 removed a force-cgroups-v2 setup for Ubuntu, possibly
assuming that Ubuntu uses cgroups v1 by default? That doesn't
seem to be the case: the Ubuntu I've looked at (via Cirrus
rerun-with-terminal) seems to default to v2. End result is
that we've been running CI for months without testing runc.
This PR forces cgroups v1 on Ubuntu, via grub boot args.
As of 2022-07-20 the version of criu in Ubuntu is broken,
which requires us to install from something called OBS.
There was some OBS-installing code present, but it didn't
lend itself to reuse, so I refactored it and added a
temporary use-criu-from-obs line with a timestamped FIXME.
Signed-off-by: Ed Santiago <santiago@redhat.com>
=> Force CgroupsV1 on Ubuntu

README.md, imgobsolete/entrypoint.sh, imgprune/entrypoint.sh, imgts/Containerfile, imgts/entrypoint.sh
For release-branches, CI VM images must be retained long-term since they
are difficult/impossible to rebuild.  A number of times, often due to
human error, these images have been accidentally lost.
Update automation tooling such that these images are specially marked
by the timestamp-updating container that runs with every CI build.
Later, when another container runs to check for disused images, ensure
the specially marked images are never deprecated or removed.  Finally
when the deletion container runs, if a deprecated image is found
specially marked, issue a loud error that will be delivered to the
podman-monitor list.
Update documentation to reflect these changes.
=> Help preserve release-branch CI VM Images

imgts/entrypoint.sh
While going through all the containers release-branches, I noticed some
repos use `release-X.Y` and others use `release-vX.Y`.  Update the imgts
version-detection regex accordingly.
=> [CI:TOOLING] Update imgts version-regex

.github/workflows/check_cirrus_cron.yml
It's a PITA to maintain duplicate code across repos.  Relatively
github-actions added a feature that allows re-using workflows
from other repos.  Use that here to reduce duplication.
=> [CI:DOCS] GHA: Re-use identical workflow from buildah repo

README.md, get_ci_vm/Containerfile, get_ci_vm/entrypoint.sh, get_ci_vm/good_repo_test/dot_cirrus.yml, get_ci_vm/good_repo_test_v2/.cirrus.yml, get_ci_vm/good_repo_test_v2/README.md, get_ci_vm/good_repo_test_v2/dot_cirrus.yml, get_ci_vm/good_repo_test_v2/hack/get_ci_vm.sh, get_ci_vm/good_repo_test_v2/mock_ec2_key, get_ci_vm/good_repo_test_v2/mock_ec2_key.pub, get_ci_vm/good_repo_test_v2/uninit_aws.output, get_ci_vm/setup.sh, get_ci_vm/test.sh
Add necessary updates to support creation/use of EC2 CI VMs with
containers-org `hack/get_ci_vm.sh` tool.
Notes:
* Only works for repositories that have Cirrus-CI setup to run tasks in
EC2
* Any `.cirrus.yml` tasks running in EC2 must define a `$EC2_INST_TYPE`
env. var (in the YAML)
* Also requires a minor update to the `hack/get_ci_vm.sh` script
contents.
Other changes:
* Moved addition of `entrypoint.sh` script in Containerfile to speed up
build/test development cycles.
* Added `awscli` tool and necessary dependencies to containers `setup.sh`.
* Updated a few GCP lines and messages to improve consistency with EC2.
* Renamed/Updated `create_gcevm()` to a generic `create_vm()` that works
with both clouds.
* Updated `fini()` and `fini_vm()` to be generic and work with both
clouds.
* Added …
=> [CI:TOOLING] Add support for EC2 instances in get_ci_vm

base_images/fedora_base-setup.sh
Long ago, many test failures and other problems were experienced in
Cirrus-CI managed google-cloud VMs.  None of the problems were
reproducible manually.  It was discovered that because the cirrus agent
starts from a metadata-downloaded script, it was executing with a more
restrictive SELinux type.  This is not the case when running tests
manually, where root sshs in.
It's been observed recently, a similar situation may be occurring in
EC2.  However, in this case, the agent is started by cloud-init, and was
observed operating with the type `cloud_init_t`.  In case this is the
source of trouble now or in the future, fix the setup to match GCP.
=> Set EC2 cirrus-agent SELinux context to unconfined

get_ci_vm/entrypoint.sh, get_ci_vm/good_repo_test_v2/.cirrus.yml, get_ci_vm/good_repo_test_v2/ami_search.json, get_ci_vm/test.sh
In response to recently added support in Cirrus-CI.  This mimics its
behavior: Search for the most recent AMI by name-tag when the image name
does not look like `ami-*`.  Also added a test to verify the complex
result-parsing remains functional over time.
Manually verified this works with both an updated and older podman
repository.
=> [CI:TOOLING] Add support for AMI name-tag search

.cirrus.yml, .github/workflows/orphan_vms.yml, Makefile, imgts/Containerfile, imgts/entrypoint.sh, imgts/lib_entrypoint.sh, orphanvms/Containerfile, orphanvms/_ec2, orphanvms/_gce, orphanvms/entrypoint.sh
VM's come from many sources (i.e. cirrus-CI, get_ci_vm, manually created, etc.).
Some VMs are quite costly to run, others hanging around may indicate an
automation or security-related problem.  So it makes sense to monitor for
any VMs hanging around more than several days.
Update the `imgts` (base) image to include the `aws` CLI tool.  Enhance
the orphanvms container image (and scripts) to print out a
human-friendly list of VMs which may have leaked.  The
github-actions-workflow `orphan_vms.yml` will run this container daily
and send an e-mail to podman-monitor with any standard-output.
=> [CI:TOOLING] Add EC2 instance support to orphanvms container

.github/workflows/orphan_vms.yml
This is somehow causing a silent failure of the workflow, with an error
coming from podman:
```
Error: error parsing env file "/tmp/env_file_<BLAH>": name "output "
has white spaces, poorly formatted name
```
This is due to the $AWSINI contents being mult-line.  Fix this by
making github-actions set the secret env. vars.  Then after making
sure they're exported, let podman figure out how to handle their
contents.
Also, split the data collection from data processing tasks to improve
debug-ability.  Rename the output file and artifact to indicate their
expected contents better.
=> [CI:DOCS] Fix error caused by multi-line $AWSINI contents

.github/workflows/orphan_vms.yml
Fix issue introduced in https://github.com/containers/automation_images/pull/171
At the time of this commit, the default github-action runners are using
an ancient version of podman.  This version does not support using the
`-e ENVAR` feature to slurp up env. var values from the environment.
They must be set on the command-line.
=> [CI:DOCS] Fix passing secret env. vars. into podman

.github/workflows/orphan_vms.yml, orphanvms/Containerfile, orphanvms/_gce, orphanvms/entrypoint.sh
This var. was always required by gcloud-init() but by re-initializing
inside a loop of other projects, gcloud apparently ignored it being an
incorrect value.  Clarify the situation by making the env. var. required
and changing the loop variable name to avoid any confusion.
This should hopefully/finally fix https://github.com/containers/automation_images/issues/173
=> [CI:DOCS] Fix missing GCPPROJECT requirement in orphanvms

.cirrus.yml, gcsupld/entrypoint.sh, imgobsolete/entrypoint.sh, imgprune/entrypoint.sh, imgts/Containerfile, imgts/entrypoint.sh, imgts/lib_entrypoint.sh, orphanvms/_ec2, orphanvms/entrypoint.sh
AWS EC2 has a separate mechanism for recording an AMI's last-used
timestamp.  However, other important metadata is also maintained on
images such as `permanent=true` (or not).  For repos. which utilize EC2,
add support for the imgts container updating EC2 images metadata.
Also, add a task to exercise the imgts container in a [CI:TOOLING]
context (where the image is built).  Set this up as a dry-run
so it doesn't depend on the images actually existing.
=> Support optional EC2 images in imgts container

.github/actions/bin/create_image_table.py, .github/workflows/pr_image_id.yml, Makefile, base_images/cloud.yml, cache_images/cloud.yml, image_builder/gce.yml
Since this GHA workflow's previous update, support has been added to
Cirrus-CI such that downstream CI can reference EC2 images by
the same `$IMAGE_SUFFIX` value used in GCP.  Overhaul the image-table
posted to PRs by this workflow, such that it reflects this, and provides
a handy-dandy link directly to the build-log for each image.  Also,
sort the table rows by the stage + image name.
=> [CI:DOCS] Overhaul image-table pr-comment workflow

.github/actions/bin/create_image_table.py
This fixes a few links in the build-id table comment posted by github actions, for example:
```
[Cirrus CI build](https://cirrus-ci.com/build/${{ steps.retro.outputs.bid }}) successful. [Found built image names and IDs](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}):
|*Stage*|**Image Name**|`IMAGE_SUFFIX`|
|---|---|---|
|*base*|[fedora](https://cirrus-ci.com/task/5523770751320064)|`b4746025087795200`|
...cut...
```
i.e. it's not filling in some of the info. from github because the script was moved from workflow in-line, to a standalone script.
=> [CI:DOCS] Fix links appearing in build-id comment post

.cirrus.yml, imgobsolete/Containerfile, imgobsolete/entrypoint.sh, imgts/Containerfile, imgts/lib_entrypoint.sh, orphanvms/_ec2
Every time images are built in this repo. it can be a dice-roll.
There's a decent possibility the build could fail or the images won't
meet the needs of downstream CI.  Additionally, when downstream CI
actually moves onto updates images, the old ones are left behind taking
up space.  Multiply this by all the repos using VMs, and it quickly
adds up to a lot of crap images hanging around.
Dealing with this mess is the job of the imgobsolete container image.
Add support to it for handling AWS EC2 images, including the required
special-handling for (release-branch) permanent=true images. Also update
the `test_imgobsolete` task to validate the changes actually functional.
Lastly, update the two related task-names to make them easier to
read/understand.
=> [CI:TOOLING] Add EC2 imgobsolete container & cirrus-cron support 

imgobsolete/entrypoint.sh
All `aws` cli commands dealing with images require specifying them by
AMI ID rather than name.  When adding EC2 images into the list for
potential deprecation, only one condition used the ID, the rest used the
image name.  This will fail randomly, depending on which items are
chosen.  Fix this by always using the AMI ID when adding to the
candidate list.  Also, stick the image name-tag into the tag list for
the benefit of humans looking at logs.
=> [CI:TOOLING] Fix imgobsolete EC2 AMI reference by name

Makefile, get_fedora_url.sh, import_images/README.md
Fixes: #190
Previously, maintainers were required to not only fill out the desired Fedora release numbers, but also manually look up six separate URLs and copy-paste their values.  This is a pain in the butt and error-prone. Add a script to perform the lookups and call the script for the required URLs only when required.  In other words, don't execute the script for `make help` or other targets that don't require the URLs.
How to test:
* From a VM with plenty of network bandwidth - Follow [the image import README](https://github.com/containers/automation_images/tree/main/import_images#readme)
* Some of the AWS operations remain less-than-reliable, see [the Failure responses section.](https://github.com/containers/automation_images/tree/main/import_images#failure-responses)
* For fun and …
=> Lookup Fedora image & checksum URLs on demand

.github/actions/bin/create_image_table.py, .github/workflows/pr_image_id.yml
Support future tooling and humans in locating the most recently built VM images.  Publish both JSON and MD formated files to a GitHub Gist.
=> Publish the latest image-build table to a gist

.github/actions/bin/create_image_table.py, .github/workflows/pr_image_id.yml
Some github actions do unexpected mangling of input paths.  Adjust all file i/o to be relative to CWD which seems to always be available regardless of context.
=> [CI:DOCS] Use paths relative to CWD

.github/workflows/pr_image_id.yml
The location of this directory changes based on having run the checkout action or not.  Since it ran later in the `pr_image_id` workflow, the python script was not able to find the `built_images.json` file.  Fix this by checking out the repository earlier in the pipeline.
=> [CI:DOCS] Fix GITHUB_WORKSPACE context

.github/actions/bin/create_image_table.py, .github/workflows/pr_image_id.yml
The md gist contains the "IMAGE_TABLE" here-document line, remove that. Also attempt to fix failure to post the JSON gist.  When it ran previously, the action reported the (unhelpful) error: "not found"
https://github.com/containers/automation_images/actions/runs/3100655221/jobs/5021168174#step:17:35
=> [CI:DOCS] Fix gist content + Missing json gist

.github/workflows/pr_image_id.yml
Apparently github-action workflow will absolutely treat the conditional 'if '' > 0' as "true".  Fix this by validating the count is a number before setting it.
=> [CI:DOCS] Fix lack of validation on comparison

get_ci_vm/good_repo_test/.cirrus.yml, lib.sh
Includes support for parsing 'windows_container' tasks.
=> [CI:TOOLING] Build updated get_ci_vm container image

Makefile
The transition has hit some operational and technical hiccups and delays. This is blocking others from doing needed updates on the old images. Fix this for everyone by reverting back to F35/36 on main.  Work on F37 will continue independently in:
https://github.com/containers/automation_images/pull/195
=> Revert update to F36/37 images

cache_images/fedora-netavark_packaging.sh
The netavark-dhcp-proxy test suite needs the dnsmasq package to serve as a DHCP server.
Signed-off-by: Brent Baude <bbaude@redhat.com>
=> add dnsmasq to netavark image

orphanvms/_gce, orphanvms/entrypoint.sh
Manual ovservation shows lost VMs from Packer which should have been picked up by this check.
=> [CI:TOOLING] Fix GCP orphan VMs detection

orphanvms/_gce
The gcloud command run for each project was not restricting it's search by project name.  This resulted in iterating multiple times over the same set of orphan search results.  Fix this by adding telling gcloud to only look in a single, specific project.
=> [CI:TOOLING] Fix orphanvms listing duplicate orphans

get_ci_vm/good_repo_test/.gitattributes
Drop LFS metadata which is inconsistent with the existing fully checked in file.
This fixes a problem where git usage on a system with git lfs fully installed will receive errors on clone, and the repo will be stuck in a permanent dirty state:
```
Cloning into 'automation_images'...
remote: Enumerating objects: 1919, done.
remote: Counting objects: 100% (267/267), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 1919 (delta 165), reused 239 (delta 144), pack-reused 1652
Receiving objects: 100% (1919/1919), 743.40 KiB | 3.18 MiB/s, done.
Resolving deltas: 100% (1322/1322), done.
Encountered 1 file that should have been a pointer, but wasn't:
get_ci_vm/good_repo_test/dot_git.tar.gz
$ git status
(use "git add <file>..." to update what will be committed)
(use "git …
```
=> [CI:DOCS] Drop LFS metadata which conflicts with checked-in file

build-push/.install.sh, build-push/test.sh
This test has been failing recently with the error:
```
************************************************
realpath: ./build-push/test.sh: No such file or directory
realpath: missing operand
Try 'realpath --help' for more information.
ERROR: Fail.  Expecting match to
'Must.be.called.with.exactly.two.arguments' or
'does.not.appear.to.be.the.root.of.a.git.repo', got:
Auto-updating build-push operational scripts...
Obtaining latest version...
Installing...
/tmp/tmp-build-push-test-LpQS
Re-executing main.sh ...
```
Attempt to fix this by running the mock `main.sh` script using it's full path and a completely clean shell environment.  Also, ensure install script fully imports the automation common lib, and not just the location & path variables.
=> Fix build-push auto-update test

.github/workflows/orphan_vms.yml, .github/workflows/pr_image_id.yml, cache_images/fedora_packaging.sh
Setting outputs this way is deprecated.  Ref:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
Other commit is minor, it just removes a hard-coded version number.
=> [CI:DOCS] Update github actions set-output usage + Ensure CNI testing in Fedora N-1 CI VM Images

.github/workflows/orphan_vms.yml
This e-mail now reports on both GCP and AWS VMs.
=> [CI:DOCS] Minor: Remove GCP from e-mail text

.cirrus.yml, Makefile, win_images/bootstrap.ps1, win_images/win-server-wsl.yml, win_images/win_packaging.ps1
This PR introduces the build of a Windows 2022 Server AMI image with WSL enabled for CI testing.
While this image is generically usable, it's primary purpose is to enable Podman CI to verify Windows functionality, which relies on an environment supporting WSL. Since WSL requires the use of virtualization, the image must be run on bare metal nodes. However, the image itself is built on lower-cost t3 instances since virt is only necessary to *run* WSL (installing does not require it).
While the intended target for Podman on Windows is Windows 10 and Windows 11 Desktop environments, AWS only supports the usage and licensing of Server builds. Since Windows Server 2022 and Windows 10 are derived from the same common baseline, 2022 is sufficient for testing (earlier versions (e.g., 2019) are …
=> Introduce Windows VM AMI with WSL enabled

cache_images/fedora-netavark_packaging.sh, cache_images/fedora_packaging.sh
=> Add wireguard-tools and passt packages

.github/workflows/check_cirrus_cron.yml
Across all other repos that use cirrus-cron jobs and report failures, the later occurs at 03:03 UTC.  Normalize the schedule of the same job in this repo to be consistent with all the others.
=> [skip-ci] Normalize cirrus-cron GHA fail-mail

cache_images/fedora_packaging.sh, cache_images/podman_tooling.sh
Commit
https://github.com/containers/podman/commit/c7827957a427c8c85c37fcb67b3d5999dd372aa7 altered the way tooling is installed for podman making it incompatible with a c/automation_images pre-install.  Several attempts were made to update podman's scripts and Makefile to de-hardcode this.  All failed and/or were too complex.  Instead, abandon the effort entirely, allowing podman to suffer any consequential runtime-install flakes or other bad behaviors.
=> Stop pre-installing podman utils/tools

cache_images/fedora-netavark_packaging.sh
mandown is required to convert a markdown document into a man page.
see https://github.com/containers/netavark/pull/534
=> netavark: install mandown into image

cache_images/fedora_setup.sh
Ref: https://github.com/containers/podman/pull/16525#issuecomment-1377651915
/cc @Luap99
=> Hard-code older F36/F37 kernel versions

win_images/auto_logon.ps1, win_images/win-server-wsl.yml, win_images/win_packaging.ps1
**NOTE win images produced by this PR will not be usable until the second half on the podman side (containers/podman#17160) is merged. That PR will bump the win image forward** 
Recently Microsoft switched from shipping WSL as part of each OS major version delivery stream to a common synchronized, and more current, one provided by the Windows store.  Apps in the Windows Store are sandboxed, either as UWP native apps, or as Desktop bridge/centennial apps as is the case with WSL. Calls to launch their respective executables are intercepted and redirected to setup the appropriate silos and run the true app. However these facilities expect usage from an interactive Windows session. 
In addition to user/kernel space separation, Windows has the notion of sessions (dates back to historical …
=> Modify windows image to pre-create an interactive session.

cache_images/fedora_packaging.sh
Install python3-devel and do not download podman-* packages as they can
be fetched from dnf.
oci-umount should no longer be needed.
Fixes: #159 and #161
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
=> Update package dependencies

ci/validate.sh
This conditional was required temporarily so #247 could merge.  Remove
and replace it with a version that avoids modifying any files and only
checks if `IMG_SFX` changes were made.
Depends on #247
=> [CI:DOCS] Resolve TODO: human-readable image-suffixes

.github/workflows/pr_image_id.yml
The c<$CIRRUS_BUILD_ID> format tags have been replaced by the contents of the IMG_SFX file.  However, this workflow does not clone the repository and so cannot access the file.  Simplify it to just use the latest tag.
=> [CI:DOCS] Fix attempted use of old tag format

.github/renovate.json5, ci/validate.sh, lib.sh
Often these kinds of updates require some hand-holding of the build process and/or manual build-script updates.  However, it's desirable to not allow CI VM images to get "too far" behind w/ their common-lib version.  Teach renovate how to manage it, try to build CI VM images, but mark the PRs as draft since they likely need more scrutiny.
=> [CI:DOCS] Renovate management of common-lib updates

import_images/README.md
Modern versions of the AWS cli allow all these options to exist in the `credentials` file.  But for completeness, and to add in the region default, best mention them.
=> [CI:DOCS] Minor readme update

.cirrus.yml
Previously the build-push task was much more sophisticated and able to run even if a new CI VM image was not produced.  This situation has now changed, and the testing task requires some additional "smarts" to not run when its image wasn't build.
Note: I have to set `[CI:DOCS]` on this otherwise the validate check barfs due to no `IMG_SFX` update.  I cannot update `IMG_SFX` due to a bunch of expired `timebomb()`s.  However, this change (and the `timebomb()`s) was successfully tested when it was originally part of https://github.com/containers/automation_images/pull/349
=> [CI:DOCS] Fix test_build-push failing w/ no_build-push label

.cirrus.yml
Previously the `tag_latest_images` was executing during the daily 'lifecycle' Cirrus-cron job.  This was unintentional, this task should only run after a merge onto the default branch.  Fix the condition.
=> [CI:DOCS] Stop tagging during cron runs

.codespelldict, .codespellrc, .gitignore, ci/Containerfile, dot_pre-commit-config.yaml.example, imgts/lib_entrypoint.sh
Add suggested/example `pre-commit` configuration for this repo. To use as-is, simply symlink to `.pre-commit-config.yaml`.  Otherwise it can be a basis for a custom configuration.
Also include codespell config w/ repo-specific dictionary extension.
Ref: https://github.com/containers/automation_images/pull/364
=> [CI:DOCS] Add example pre-commit config

.github/renovate.json5
Previously the Renovate configuration was using an older format no longer supported by the bot.  Apply automatic fixes proposed by the bot, re-adding/adjusting the old comments as needed.
Also:
* Drop automatic assignment of Renovate PRs to `cevich`
* Reference the GHCR registry container image
* Simplify CI VM update warning message conditions & text.
=> [CI:DOCS] Reformat renovate config + other minor updates

.github/renovate.json5
Previously Renovate was failing in a multi-line search for an anchored pattern in `lib.sh`.  This resulted in it completely ignoring the custom regex manager for that file, as observed in the debug logs.  Fix this by removing the regex anchors.
Also remove the filename anchors referenced in the `lib.sh` package rule as they're unnecessary.
=> [CI:DOCS] Fix renovate updating lib.sh

README.md
Previously this was available in `import_images/README.md` which was recently removed.  Since this page is difficult to find in the AWS docs, link it directly into the main README.
=> [CI:DOCS] Add link to AWS credentials file format

gcpprojects.txt
This github repo has been archived, CI disabled, and the GCE project
deleted.  Stop tracking it in automation.
Also update the comment in the file.
=> [CI:DOCS] Retire oversight of dnsname project 
